channels:
  - socket_name: can1
    dbc_file_name: /home/test/Git/Charger/dbc/CAN4_Accu_1.dbc
    log_file_name: ../Logs/CAN4
    receive_ip: 127.0.0.1
    receive_port: 9870
    mcap_logging: true
    udp_publishing: false
    ignore_msgs: []

  - socket_name: can0
    dbc_file_name: /home/test/Git/Charger/dbc/CAN7_UASA2209_Accu_2.dbc
    log_file_name: ../Logs/CAN7
    receive_ip: 127.0.0.1
    receive_port: 9870
    mcap_logging: true
    udp_publishing: false
    ignore_msgs: []

